/* MaxLoad — trusted input bridge (client side).
 *
 * Maximo ignores synthetic (isTrusted=false) events, so real clicks/typing are
 * generated by the service worker via the DevTools Protocol. This module maps a
 * target element (in any same-origin frame) to TOP-LEVEL viewport coordinates
 * and asks the worker to dispatch real OS input there. Falls back to synthetic
 * events if the debugger isn't available.
 */
(function () {
  "use strict";
  const MaxLoad = window.MaxLoad;

  /** Center of `el` expressed in the top-level page's viewport coordinates,
   *  summing each enclosing iframe's offset (same-origin frames only). */
  function topCoords(el) {
    const r = el.getBoundingClientRect();
    let x = r.left + r.width / 2;
    let y = r.top + r.height / 2;
    let win = el.ownerDocument.defaultView;
    let guard = 0;
    while (win && win !== win.parent && guard++ < 12) {
      let fe = null;
      try {
        fe = win.frameElement;
      } catch (_) {
        break; // cross-origin — can't map further
      }
      if (!fe) break;
      const fr = fe.getBoundingClientRect();
      x += fr.left;
      y += fr.top;
      win = win.parent;
    }
    return { x: Math.round(x), y: Math.round(y) };
  }

  /** If the click point sits under MaxLoad's own panel, hide the panel for the
   *  duration of the click so the OS click lands on the page (a Maximo dialog
   *  button), not our toolbar. Returns a restore fn (or null). */
  function uncoverPanel(x, y) {
    const host = document.getElementById("maxload-panel-host");
    if (!host || host.style.display === "none") return null;
    const r = host.getBoundingClientRect();
    if (x >= r.left && x <= r.right && y >= r.top && y <= r.bottom) {
      host.style.visibility = "hidden";
      return () => {
        host.style.visibility = "";
      };
    }
    return null;
  }

  /** Read the current value/text of a field, for read-back verification. */
  function readVal(el) {
    if (!el) return "";
    const role = (el.getAttribute && (el.getAttribute("role") || "").toLowerCase()) || "";
    if (
      el.isContentEditable ||
      (el.getAttribute && (el.getAttribute("contenteditable") || "") === "true") ||
      (el.tagName !== "INPUT" && el.tagName !== "TEXTAREA" && role === "textbox")
    ) {
      return (el.textContent || "").trim();
    }
    return String(el.value == null ? "" : el.value).trim();
  }

  /**
   * Scroll `el` to a settled position and return trustworthy TOP-LEVEL click
   * coordinates — or null when the point can't be trusted (off-screen in its
   * frame, zero-size, or the spot is covered by something else). Returning null
   * makes the caller act on the exact element reference instead, so a scroll or
   * layout shift can never send the click/keystroke to a NEIGHBOURING control.
   */
  async function stableCoords(el) {
    try { el.scrollIntoView({ block: "center", inline: "center" }); } catch (_) {}
    // wait for the scroll + any async re-render to settle, so the point we
    // measure is where the element actually is at dispatch time — not a fixed
    // delay that can fire mid-scroll.
    if (MaxLoad.settle) await MaxLoad.settle.waitForSettle({ quietMs: 120, timeoutMs: 1000 });
    else await MaxLoad.util.sleep(120);

    const doc = el.ownerDocument;
    const win = doc.defaultView || window;
    const r = el.getBoundingClientRect();
    if (r.width < 1 || r.height < 1) return null;
    const lx = r.left + r.width / 2;
    const ly = r.top + r.height / 2;
    // must be inside its own frame's viewport
    if (lx < 0 || ly < 0 || lx > win.innerWidth || ly > win.innerHeight) return null;
    // hit-test: the spot must resolve to the target (or a child/parent of it).
    // If something else is there, a scroll/overlay moved things — refuse the
    // coordinate click and let the caller act on the element directly.
    let hit = null;
    try { hit = doc.elementFromPoint(lx, ly); } catch (_) {}
    if (hit && hit !== el && !el.contains(hit) && !hit.contains(el)) return null;

    const { x, y } = topCoords(el);
    if (x <= 0 || y <= 0) return null;
    return { x, y };
  }

  async function click(el) {
    if (!el) return false;
    const c = await stableCoords(el);
    if (!c) return MaxLoad.util.realClick(el); // can't trust the point -> exact element
    const restore = uncoverPanel(c.x, c.y);
    try {
      const r = await chrome.runtime.sendMessage({ type: "ml:cdp:click", x: c.x, y: c.y });
      if (r && r.ok) return true;
      MaxLoad.warn("cdp click failed, synthetic fallback: " + (r && r.error));
    } catch (e) {
      MaxLoad.warn("cdp click message failed: " + String(e));
    } finally {
      if (restore) restore();
    }
    return MaxLoad.util.realClick(el);
  }

  async function settleShort(timeoutMs) {
    if (MaxLoad.settle) await MaxLoad.settle.waitForSettle({ quietMs: 120, timeoutMs: timeoutMs || 1200 });
    else await MaxLoad.util.sleep(150);
  }

  /** Did `value` end up in THIS element? Lenient — Maximo may reformat/expand. */
  function didLand(el, before, want) {
    const after = readVal(el);
    return after !== before || after === want || (!!want && after.includes(want));
  }

  function commitField(el) {
    try {
      el.dispatchEvent(new Event("change", { bubbles: true }));
      el.dispatchEvent(new Event("blur", { bubbles: true }));
    } catch (_) {}
    return true;
  }

  /**
   * PRIMARY typing path — coordinate-free. Focus the element in JS (the browser
   * scrolls it into view natively) then insert TRUSTED text into the focused
   * node via CDP. Because insertText follows focus (not a pixel), this is immune
   * to scroll position, off-screen fields, overlays, and the mouse moving during
   * a run. Returns false if focus can't be confirmed, so the caller falls back
   * to the coordinate path.
   */
  async function focusType(el, value, commitKey) {
    try {
      el.scrollIntoView({ block: "center", inline: "center" });
      el.focus({ preventScroll: true });
    } catch (_) {}
    const doc = el.ownerDocument;
    const active = doc.activeElement;
    const focused =
      active === el ||
      (el.contains && active && el.contains(active)) ||
      (active && active.contains && active.contains(el));
    if (!focused) return false; // focus didn't land -> use coordinate fallback
    try {
      const r = await chrome.runtime.sendMessage({
        type: "ml:cdp:type-focused",
        text: String(value),
        commitKey: commitKey || "tab"
      });
      return !!(r && r.ok);
    } catch (e) {
      MaxLoad.warn("cdp type-focused message failed: " + String(e));
      return false;
    }
  }

  async function type(el, value, commitKey) {
    if (!el) return false;
    const before = readVal(el);
    const want = String(value == null ? "" : value).trim();

    // 1. coordinate-free focus + insertText (handles off-screen/scroll/mouse).
    if (await focusType(el, value, commitKey)) {
      await settleShort(1200);
      if (didLand(el, before, want)) return commitField(el);
    }

    // 2. trusted click at settled + hit-tested coordinates, then type there.
    const c = await stableCoords(el);
    if (c) {
      const restore = uncoverPanel(c.x, c.y);
      try {
        await chrome.runtime.sendMessage({
          type: "ml:cdp:type",
          x: c.x,
          y: c.y,
          text: String(value),
          commitKey: commitKey || "tab"
        });
      } catch (e) {
        MaxLoad.warn("cdp type message failed: " + String(e));
      } finally {
        if (restore) restore();
      }
      await settleShort(1200);
      if (didLand(el, before, want)) return commitField(el);
    }

    // 3. last resort — set the value straight onto the correct element so it can
    //    never end up in a NEIGHBOURING field.
    MaxLoad.warn(`typed value didn't land in "${el.name || el.id || el.tagName}" (scroll/focus drift?) — correcting directly`);
    MaxLoad.util.realClick(el);
    syntheticSet(el, value);
    return false;
  }

  function syntheticSet(el, value) {
    try {
      // rich-text / contenteditable (no .value) — set editable content
      const rich =
        el.isContentEditable ||
        (el.getAttribute && (el.getAttribute("contenteditable") || "") === "true") ||
        (el.tagName !== "INPUT" && el.tagName !== "TEXTAREA" && el.getAttribute && (el.getAttribute("role") || "").toLowerCase() === "textbox");
      if (rich) {
        el.focus();
        el.textContent = String(value);
      } else {
        const proto = Object.getPrototypeOf(el);
        const desc =
          Object.getOwnPropertyDescriptor(el, "value") || Object.getOwnPropertyDescriptor(proto, "value");
        if (desc && desc.set) desc.set.call(el, value);
        else el.value = value;
      }
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
      el.dispatchEvent(new Event("blur", { bubbles: true }));
    } catch (_) {}
  }

  const KEYMAP = {
    enter: { key: "Enter", code: "Enter", vk: 13 },
    tab: { key: "Tab", code: "Tab", vk: 9 },
    escape: { key: "Escape", code: "Escape", vk: 27 },
    esc: { key: "Escape", code: "Escape", vk: 27 },
    arrowdown: { key: "ArrowDown", code: "ArrowDown", vk: 40 },
    arrowup: { key: "ArrowUp", code: "ArrowUp", vk: 38 }
  };

  /** Press a key (trusted, via CDP) on whatever is focused; synthetic fallback. */
  async function pressKey(keyName) {
    const k = KEYMAP[String(keyName || "").toLowerCase()] || { key: keyName, code: keyName, vk: 0 };
    try {
      const r = await chrome.runtime.sendMessage({ type: "ml:cdp:key", key: k.key, code: k.code, vk: k.vk });
      if (r && r.ok) return true;
      MaxLoad.warn("cdp key failed, synthetic fallback: " + (r && r.error));
    } catch (e) {
      MaxLoad.warn("cdp key message failed: " + String(e));
    }
    try {
      const el = document.activeElement || document.body;
      const K = (el.ownerDocument.defaultView || window).KeyboardEvent || KeyboardEvent;
      const opt = { key: k.key, code: k.code, keyCode: k.vk, which: k.vk, bubbles: true, cancelable: true };
      el.dispatchEvent(new K("keydown", opt));
      el.dispatchEvent(new K("keypress", opt));
      el.dispatchEvent(new K("keyup", opt));
    } catch (_) {}
    return false;
  }

  async function detach() {
    try {
      await chrome.runtime.sendMessage({ type: "ml:cdp:detach" });
    } catch (_) {}
  }

  MaxLoad.input = { click, type, pressKey, detach, topCoords };
})();
