/* MaxLoad — trusted input bridge (client side).
 *
 * Maximo ignores synthetic (isTrusted=false) events, so real clicks/typing are
 * generated by the service worker via the DevTools Protocol. This module maps a
 * target element (in any same-origin frame) to TOP-LEVEL viewport coordinates
 * and asks the worker to dispatch real OS input there. Falls back to synthetic
 * events if the debugger isn't available.
 */
(function () {
  "use strict";
  const MaxLoad = window.MaxLoad;

  /** Center of `el` expressed in the top-level page's viewport coordinates,
   *  summing each enclosing iframe's offset (same-origin frames only). */
  function topCoords(el) {
    const r = el.getBoundingClientRect();
    let x = r.left + r.width / 2;
    let y = r.top + r.height / 2;
    let win = el.ownerDocument.defaultView;
    let guard = 0;
    while (win && win !== win.parent && guard++ < 12) {
      let fe = null;
      try {
        fe = win.frameElement;
      } catch (_) {
        break; // cross-origin — can't map further
      }
      if (!fe) break;
      const fr = fe.getBoundingClientRect();
      x += fr.left;
      y += fr.top;
      win = win.parent;
    }
    return { x: Math.round(x), y: Math.round(y) };
  }

  /** If the click point sits under MaxLoad's own panel, hide the panel for the
   *  duration of the click so the OS click lands on the page (a Maximo dialog
   *  button), not our toolbar. Returns a restore fn (or null). */
  function uncoverPanel(x, y) {
    const host = document.getElementById("maxload-panel-host");
    if (!host || host.style.display === "none") return null;
    const r = host.getBoundingClientRect();
    if (x >= r.left && x <= r.right && y >= r.top && y <= r.bottom) {
      host.style.visibility = "hidden";
      return () => {
        host.style.visibility = "";
      };
    }
    return null;
  }

  async function click(el) {
    if (!el) return false;
    try {
      el.scrollIntoView({ block: "center", inline: "center" });
    } catch (_) {}
    await MaxLoad.util.sleep(70);
    const { x, y } = topCoords(el);
    if (x <= 0 || y <= 0) return MaxLoad.util.realClick(el); // off-screen
    const restore = uncoverPanel(x, y);
    try {
      const r = await chrome.runtime.sendMessage({ type: "ml:cdp:click", x, y });
      if (r && r.ok) return true;
      MaxLoad.warn("cdp click failed, synthetic fallback: " + (r && r.error));
    } catch (e) {
      MaxLoad.warn("cdp click message failed: " + String(e));
    } finally {
      if (restore) restore();
    }
    return MaxLoad.util.realClick(el);
  }

  async function type(el, value, commitKey) {
    if (!el) return false;
    try {
      el.scrollIntoView({ block: "center" });
    } catch (_) {}
    await MaxLoad.util.sleep(50);
    const { x, y } = topCoords(el);
    if (x <= 0 || y <= 0) {
      MaxLoad.util.realClick(el);
      syntheticSet(el, value);
      return false;
    }
    const restore = uncoverPanel(x, y);
    try {
      const r = await chrome.runtime.sendMessage({
        type: "ml:cdp:type",
        x,
        y,
        text: String(value),
        commitKey: commitKey || "tab"
      });
      if (r && r.ok) {
        try {
          el.dispatchEvent(new Event("change", { bubbles: true }));
          el.dispatchEvent(new Event("blur", { bubbles: true }));
        } catch (_) {}
        return true;
      }
      MaxLoad.warn("cdp type failed, synthetic fallback: " + (r && r.error));
    } catch (e) {
      MaxLoad.warn("cdp type message failed: " + String(e));
    } finally {
      if (restore) restore();
    }
    MaxLoad.util.realClick(el);
    syntheticSet(el, value);
    return false;
  }

  function syntheticSet(el, value) {
    try {
      const proto = Object.getPrototypeOf(el);
      const desc =
        Object.getOwnPropertyDescriptor(el, "value") || Object.getOwnPropertyDescriptor(proto, "value");
      if (desc && desc.set) desc.set.call(el, value);
      else el.value = value;
      el.dispatchEvent(new Event("input", { bubbles: true }));
      el.dispatchEvent(new Event("change", { bubbles: true }));
      el.dispatchEvent(new Event("blur", { bubbles: true }));
    } catch (_) {}
  }

  async function detach() {
    try {
      await chrome.runtime.sendMessage({ type: "ml:cdp:detach" });
    } catch (_) {}
  }

  MaxLoad.input = { click, type, detach, topCoords };
})();
